from abc import ABCMeta, abstractmethod

class AbstractStrategy(metaclass=ABCMeta):
    """
        Strategy is an abstract base class providing an interface for
        all subsequent (inherited) strategy handling objects.

        The goal of a (derived) Strategy object is to generate Signal
        objects for particular symbols based on the inputs of Bars
        (OLHCVI) generated by a DataHandler object.

        This is designed to work both with historic and live data as
        the Strategy object is agnostic to the data source,
        since it obtains the bar tuples from a queue object.
        """
    @abstractmethod
    def calculate_signals(self):
        """
               Provides the mechanisms to calculate the list of signals.
               """
        raise NotImplementedError

    @abstractmethod
    def plot(self):
        raise NotImplementedError
